general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
bold = { family = "JetBrainsMono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }
offset = { y = 3 }
size = 11

[window]
padding.x = 8
padding.y = 8
decorations = "None"

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]
