general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrains Mono" }
bold = { family = "JetBrains Mono" }
italic = { family = "JetBrains Mono" }
offset = { y = 2 }
size = 10

[window]
padding.x = 6
padding.y = 6
decorations = "None"

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]
